export const COMMENTS=[
  {
    "Id": "5f6610c06576178ad5a4bd6a",
    "Country": "Australia",
    "Brand": "IT",
    "Region": "East",
    "Office": "Melbourne",
    "CommentType": "Client Contact",
    "EntityName": "blue",
    "EntityNumber": 3943,
    "CommentDate": "2015-11-19T03:35:54 -11:00",
    "ClientName": "ZIALACTIC",
    "ClientNo": 7772,
    "CandidateName": "Crawford Shepard",
    "CandidateNo": 1428,
    "ContactName": "Gomez Malone",
    "CreateDate": "2016-12-14T06:21:05 -11:00",
    "CommentTime": "2014-03-11T10:17:56 -11:00",
    "CreatedBy": "Kristine Hickman",
    "StandardDescription": "Job Extension",
    "Comment": "Nisi est enim laborum ex cupidatat laborum sit occaecat. Ut velit aliqua et irure adipisicing nisi voluptate ad eiusmod. Laboris consectetur culpa duis sint.\r\n"
  },
  {
    "Id": "5f6610c00ea2ffc83a8f0d10",
    "Country": "Singapore",
    "Brand": "Industrial",
    "Region": "South",
    "Office": "Melbourne",
    "CommentType": "Cost Centre",
    "EntityName": "green",
    "EntityNumber": 9338,
    "CommentDate": "2014-04-14T06:13:48 -10:00",
    "ClientName": "SULTRAXIN",
    "ClientNo": 4401,
    "CandidateName": "Alexis Guerrero",
    "CandidateNo": 2955,
    "ContactName": "Booker Buckner",
    "CreateDate": "2020-05-14T02:27:42 -10:00",
    "CommentTime": "2014-05-30T04:15:30 -10:00",
    "CreatedBy": "Corrine Flynn",
    "StandardDescription": "Complaint,",
    "Comment": "Incididunt tempor ea irure culpa sint velit culpa sit occaecat. Excepteur dolore enim est consequat culpa non dolore minim tempor exercitation ea. Aute est occaecat ipsum ex anim adipisicing. Amet ut veniam consectetur elit consectetur aliqua ea non et dolor eiusmod. Adipisicing est et non nulla culpa. Ut sint nostrud nulla ullamco ea. Commodo est do enim incididunt excepteur laborum quis nulla amet.\r\n"
  },
  {
    "Id": "5f6610c077e9263b84ee034f",
    "Country": "Australia",
    "Brand": "Logistics",
    "Region": "East",
    "Office": "Singapore",
    "CommentType": "Client Contact",
    "EntityName": "green",
    "EntityNumber": 8995,
    "CommentDate": "2019-02-16T10:55:55 -11:00",
    "ClientName": "ZOMBOID",
    "ClientNo": 2557,
    "CandidateName": "Short Fields",
    "CandidateNo": 3823,
    "ContactName": "Daisy Sellers",
    "CreateDate": "2019-04-08T02:42:59 -10:00",
    "CommentTime": "2017-12-08T02:41:00 -11:00",
    "CreatedBy": "Ellis May",
    "StandardDescription": "Complaint,",
    "Comment": "Laborum minim dolore duis adipisicing est velit cupidatat laborum commodo in. Amet mollit ad nostrud id velit proident anim laboris veniam. Do in anim esse consectetur nisi magna velit id ipsum ea est voluptate occaecat ex. Duis adipisicing nulla quis consequat Lorem sit ut culpa consectetur fugiat. Nisi minim in reprehenderit culpa elit mollit irure irure ut irure duis eiusmod ex veniam.\r\n"
  },
  {
    "Id": "5f6610c0a0a602994dcbc95c",
    "Country": "New Zealand",
    "Brand": "Logistics",
    "Region": "South",
    "Office": "Auckland",
    "CommentType": "Candidate",
    "EntityName": "green",
    "EntityNumber": 6804,
    "CommentDate": "2019-05-10T04:03:52 -10:00",
    "ClientName": "INJOY",
    "ClientNo": 1914,
    "CandidateName": "Sheila Edwards",
    "CandidateNo": 8398,
    "ContactName": "Cruz Byrd",
    "CreateDate": "2020-08-12T04:23:04 -10:00",
    "CommentTime": "2018-06-02T12:18:24 -10:00",
    "CreatedBy": "Carson Cox",
    "StandardDescription": "Sales Call",
    "Comment": "Minim sunt do est quis qui adipisicing ex aliquip nulla mollit ipsum. Non occaecat occaecat veniam ipsum aliquip et. Consequat cupidatat consectetur ullamco Lorem sint culpa enim qui ad ad in quis.\r\n"
  },
  {
    "Id": "5f6610c069e865ae915c999b",
    "Country": "Singapore",
    "Brand": "Industrial",
    "Region": "South",
    "Office": "Melbourne",
    "CommentType": "Client Contact",
    "EntityName": "brown",
    "EntityNumber": 9650,
    "CommentDate": "2017-11-02T03:49:37 -11:00",
    "ClientName": "XYQAG",
    "ClientNo": 2495,
    "CandidateName": "Gibbs Kaufman",
    "CandidateNo": 4229,
    "ContactName": "Della Conrad",
    "CreateDate": "2020-05-09T07:39:48 -10:00",
    "CommentTime": "2016-08-03T06:24:03 -10:00",
    "CreatedBy": "Mayer Baird",
    "StandardDescription": "Complaint,",
    "Comment": "Deserunt proident officia ex sunt esse non adipisicing velit et consequat Lorem sunt laboris nisi. Amet ea non esse dolor enim laboris aliqua minim officia sit commodo aliqua in pariatur. Nulla mollit exercitation sint anim qui id exercitation esse voluptate cupidatat ea dolor irure velit.\r\n"
  },
  {
    "Id": "5f6610c058e4621c2882fd86",
    "Country": "New Zealand",
    "Brand": "Logistics",
    "Region": "West",
    "Office": "Auckland",
    "CommentType": "Job Order",
    "EntityName": "brown",
    "EntityNumber": 4538,
    "CommentDate": "2020-06-25T09:14:46 -10:00",
    "ClientName": "DOGNOSIS",
    "ClientNo": 5470,
    "CandidateName": "Anita Maldonado",
    "CandidateNo": 4018,
    "ContactName": "Ophelia Dotson",
    "CreateDate": "2016-10-22T03:55:37 -11:00",
    "CommentTime": "2017-09-11T07:11:35 -10:00",
    "CreatedBy": "Sofia Cleveland",
    "StandardDescription": "Sales Call",
    "Comment": "Sunt qui adipisicing veniam sunt eu sit consectetur deserunt dolor cupidatat nulla mollit. Proident ipsum officia dolor quis non exercitation. Reprehenderit aute elit eu anim. Irure aute nulla in nisi laboris velit incididunt eu fugiat. Aliquip ad culpa incididunt esse incididunt tempor id esse consectetur duis et. Eiusmod deserunt qui exercitation pariatur nisi id pariatur.\r\n"
  },
  {
    "Id": "5f6610c00d01fccbafc10717",
    "Country": "Singapore",
    "Brand": "IT",
    "Region": "East",
    "Office": "Melbourne",
    "CommentType": "Timesheet",
    "EntityName": "brown",
    "EntityNumber": 8288,
    "CommentDate": "2017-08-04T04:45:22 -10:00",
    "ClientName": "SKYPLEX",
    "ClientNo": 7025,
    "CandidateName": "Holloway Romero",
    "CandidateNo": 1303,
    "ContactName": "Corine Summers",
    "CreateDate": "2019-08-01T09:47:43 -10:00",
    "CommentTime": "2018-06-24T02:54:12 -10:00",
    "CreatedBy": "Simmons Solomon",
    "StandardDescription": "Complaint,",
    "Comment": "Cupidatat adipisicing incididunt dolor eiusmod anim ex enim enim non veniam. Aute exercitation exercitation aliquip fugiat quis velit reprehenderit ad nulla fugiat dolor. Velit quis proident aliqua ipsum officia sit mollit dolor fugiat nisi. Consequat incididunt cillum culpa in mollit tempor proident amet ut pariatur ex. Veniam amet commodo eu consectetur sit velit occaecat occaecat aliqua. Eu laborum pariatur qui aliqua do quis aute consequat irure.\r\n"
  },
  {
    "Id": "5f6610c00c8eadd56d948a56",
    "Country": "Singapore",
    "Brand": "Industrial",
    "Region": "North",
    "Office": "Singapore",
    "CommentType": "Cost Centre",
    "EntityName": "blue",
    "EntityNumber": 8335,
    "CommentDate": "2016-02-14T02:31:58 -11:00",
    "ClientName": "ENORMO",
    "ClientNo": 6763,
    "CandidateName": "Blevins Roman",
    "CandidateNo": 3777,
    "ContactName": "Effie Butler",
    "CreateDate": "2019-07-26T05:55:56 -10:00",
    "CommentTime": "2019-11-15T07:48:30 -11:00",
    "CreatedBy": "Bradford Mosley",
    "StandardDescription": "Sales Call",
    "Comment": "Ut non nisi labore commodo irure nisi eiusmod aute tempor eiusmod commodo occaecat in et. Nostrud excepteur eiusmod qui ipsum adipisicing culpa nisi quis labore. Aliquip nisi exercitation enim labore commodo quis veniam magna culpa irure ut amet. Enim quis aliqua labore amet. Eiusmod dolore voluptate ut tempor. Lorem amet nisi eiusmod reprehenderit incididunt minim sit dolore proident.\r\n"
  },
  {
    "Id": "5f6610c042dd1c879cf65d8e",
    "Country": "New Zealand",
    "Brand": "Industrial",
    "Region": "South",
    "Office": "Melbourne",
    "CommentType": "Client",
    "EntityName": "blue",
    "EntityNumber": 9439,
    "CommentDate": "2018-11-25T03:32:10 -11:00",
    "ClientName": "MAROPTIC",
    "ClientNo": 3713,
    "CandidateName": "Wilcox Sweet",
    "CandidateNo": 5472,
    "ContactName": "Gonzales Little",
    "CreateDate": "2018-07-17T01:43:17 -10:00",
    "CommentTime": "2017-12-30T01:23:35 -11:00",
    "CreatedBy": "Hattie Rasmussen",
    "StandardDescription": "Sales Call",
    "Comment": "Veniam dolore Lorem esse enim qui cupidatat duis excepteur cupidatat velit tempor elit. Ut aliquip eiusmod anim do amet ad labore magna culpa id occaecat excepteur. Elit laborum id commodo anim ipsum nostrud cillum sit nisi sint tempor deserunt proident.\r\n"
  },
  {
    "Id": "5f6610c0d6418d710b3e1b4e",
    "Country": "New Zealand",
    "Brand": "Logistics",
    "Region": "South",
    "Office": "Singapore",
    "CommentType": "Candidate",
    "EntityName": "blue",
    "EntityNumber": 6368,
    "CommentDate": "2015-08-02T10:41:22 -10:00",
    "ClientName": "GRAINSPOT",
    "ClientNo": 7625,
    "CandidateName": "Kelley Craig",
    "CandidateNo": 6757,
    "ContactName": "Kenya Pena",
    "CreateDate": "2014-08-01T03:32:19 -10:00",
    "CommentTime": "2017-09-30T12:31:23 -10:00",
    "CreatedBy": "Bailey Griffith",
    "StandardDescription": "Sales Call",
    "Comment": "Aliqua cupidatat consectetur do excepteur proident ut non reprehenderit. Duis sint aute adipisicing ullamco dolore in ea Lorem incididunt consectetur nulla nostrud consectetur sint. Consequat tempor occaecat aliqua do excepteur aute incididunt ullamco. Adipisicing nisi sint amet velit excepteur nostrud deserunt ad do duis et officia occaecat consequat. Nisi id qui nisi elit incididunt consectetur eu labore fugiat et ex qui Lorem. Officia excepteur quis sint commodo eu nulla esse eiusmod dolore laboris in nisi est sunt. Elit laboris laborum minim amet sunt nulla dolore culpa fugiat sit excepteur.\r\n"
  },
  {
    "Id": "5f6610c00667ce1e967b5d33",
    "Country": "New Zealand",
    "Brand": "Industrial",
    "Region": "South",
    "Office": "Singapore",
    "CommentType": "Timesheet",
    "EntityName": "blue",
    "EntityNumber": 6181,
    "CommentDate": "2019-12-08T05:07:50 -11:00",
    "ClientName": "EXOSPEED",
    "ClientNo": 9214,
    "CandidateName": "Corina Morin",
    "CandidateNo": 9597,
    "ContactName": "Dickerson Durham",
    "CreateDate": "2018-04-02T02:24:24 -10:00",
    "CommentTime": "2017-11-30T10:27:39 -11:00",
    "CreatedBy": "Larsen Huber",
    "StandardDescription": "Job Extension",
    "Comment": "Ullamco pariatur quis sint aliquip ex nulla elit quis deserunt fugiat voluptate nostrud est. Laborum magna amet est veniam. Irure anim sit non tempor laboris. Dolor occaecat ut veniam veniam aliqua mollit ipsum qui. Sit Lorem excepteur nisi velit non velit duis amet mollit quis voluptate proident tempor ea.\r\n"
  },
  {
    "Id": "5f6610c09ed8cc8c4ffa5b6f",
    "Country": "New Zealand",
    "Brand": "Logistics",
    "Region": "East",
    "Office": "Auckland",
    "CommentType": "Timesheet",
    "EntityName": "blue",
    "EntityNumber": 6117,
    "CommentDate": "2017-07-30T09:13:22 -10:00",
    "ClientName": "QUONK",
    "ClientNo": 1567,
    "CandidateName": "Lilly Ortega",
    "CandidateNo": 7595,
    "ContactName": "Doreen Wiley",
    "CreateDate": "2019-05-20T08:35:49 -10:00",
    "CommentTime": "2016-06-29T07:03:31 -10:00",
    "CreatedBy": "Craig Mccoy",
    "StandardDescription": "Job Extension",
    "Comment": "Magna amet exercitation sit reprehenderit do aliquip occaecat ipsum nisi aute sunt anim. Duis pariatur aliqua laborum consectetur ad dolore irure laborum ad voluptate. Adipisicing Lorem sunt aute mollit laborum duis veniam occaecat nulla sunt ut ipsum.\r\n"
  }
]
