export interface IComment{
Country:String
Brand:String
Region:String
Office:String
CommentType:String
EntityName:String
EntityNumber:String
CommentDate:any
ClientName:String
ClientNo:String
CandidateName:String
CandidateNo:String
ContactName:String
CreateDate:any
CommentTime:any
CreatedBy:String
StandardDescription:String
Comment:String
}

let columns=[
"Country",
"Brand",
"Region",
"Office",
"CommentType",
"EntityName",
"EntityNumber",
"CommentDate",
"ClientName",
"ClientNo",
"CandidateName",
"CandidateNo",
"ContactName",
"CreateDate",
"CommentTime",
"CreatedBy",
"StandardDescription",
"Comment"];
